Repository KUSITMS-MOAMOA/MOAMOA_BE_V2, pull requests merged in 2025-02, with the labels that each got.

#13 [Feat/#10] : OpenAI 에러 발생 시 클로바로 대체 기능 추가
  src/main/java/corecord/dev/domain/chat/infra/openai/application/OpenAiChatService.java
Labels: Feat 💙

#14 [Refactor/#12] : 채팅 문구 변경
  src/main/java/corecord/dev/domain/chat/application/ChatService.java
Labels: Refactor🌿

#15 [Refactor/#11] 역량 분석 기능 AI 연결 확장
  src/main/java/corecord/dev/common/config/OpenAIConfig.java
  src/main/java/corecord/dev/common/config/SwaggerConfig.java
  src/main/java/corecord/dev/common/util/ClovaUtil.java
  src/main/java/corecord/dev/common/web/UserIdArgumentResolver.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisAIService.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisService.java
  src/main/java/corecord/dev/domain/analysis/infra/clova/application/ClovaAnalysisAIService.java
  src/main/java/corecord/dev/domain/analysis/infra/clova/dto/request/ClovaAnalysisRequest.java
  src/main/java/corecord/dev/domain/analysis/infra/openai/application/OpenAiAnalysisAIService.java
  src/main/java/corecord/dev/domain/chat/infra/clova/application/ClovaChatAIService.java
  src/main/java/corecord/dev/domain/chat/infra/clova/dto/request/ClovaChatRequest.java
  src/main/java/corecord/dev/domain/chat/infra/openai/application/OpenAiChatAIService.java
  src/test/java/corecord/dev/ability/service/AbilityServiceTest.java
  src/test/java/corecord/dev/analysis/service/AnalysisServiceTest.java
  src/test/java/corecord/dev/auth/util/JwtUtilTest.java
  src/test/java/corecord/dev/chat/service/ChatServiceTest.java
  src/test/java/corecord/dev/record/memo/service/MemoRecordServiceTest.java
  src/test/java/corecord/dev/user/service/UserServiceTest.java
Labels: Refactor🌿, Feat 💙

#19 [Chore/#18] 경험 기록 리스트 조회 API response dto 수정
  src/main/java/corecord/dev/domain/record/application/RecordService.java
  src/main/java/corecord/dev/domain/record/domain/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/domain/dto/response/RecordResponse.java
  src/main/java/corecord/dev/domain/record/presentation/RecordController.java
Labels: Chore ⚙️

#20 [Refactor/#16] 불필요한 DB 접근 제거 및 서비스 Interface 생성
  src/main/java/corecord/dev/domain/ability/application/AbilityDbService.java
  src/main/java/corecord/dev/domain/ability/application/AbilityService.java
  src/main/java/corecord/dev/domain/ability/application/AbilityServiceImpl.java
  src/main/java/corecord/dev/domain/ability/domain/entity/Ability.java
  src/main/java/corecord/dev/domain/ability/domain/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisService.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisServiceImpl.java
  src/main/java/corecord/dev/domain/analysis/domain/repository/AnalysisRepository.java
  src/main/java/corecord/dev/domain/chat/application/ChatDbService.java
  src/main/java/corecord/dev/domain/chat/application/ChatService.java
  src/main/java/corecord/dev/domain/chat/application/ChatServiceImpl.java
  src/main/java/corecord/dev/domain/chat/domain/repository/ChatRoomRepository.java
  src/main/java/corecord/dev/domain/folder/application/FolderDbService.java
  src/main/java/corecord/dev/domain/folder/application/FolderService.java
  src/main/java/corecord/dev/domain/folder/application/FolderServiceImpl.java
  src/main/java/corecord/dev/domain/folder/domain/repository/FolderRepository.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/application/RecordService.java
  src/main/java/corecord/dev/domain/record/application/RecordServiceImpl.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/presentation/RecordController.java
  src/main/java/corecord/dev/domain/user/application/UserService.java
  src/main/java/corecord/dev/domain/user/application/UserServiceImpl.java
  src/test/java/corecord/dev/analysis/service/AnalysisServiceTest.java
  src/test/java/corecord/dev/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/corecord/dev/chat/service/ChatServiceTest.java
  src/test/java/corecord/dev/folder/repository/FolderRepositoryTest.java
  src/test/java/corecord/dev/folder/service/FolderServiceTest.java
  src/test/java/corecord/dev/record/memo/repository/MemoRecordRepositoryTest.java
  src/test/java/corecord/dev/record/memo/service/MemoRecordServiceTest.java
Labels: Refactor🌿, Chore ⚙️

#21 [Feat/#17] : AI 만족도 조사 기능 추가
  src/main/java/corecord/dev/domain/ability/application/AbilityDbService.java
  src/main/java/corecord/dev/domain/ability/application/AbilityServiceImpl.java
  src/main/java/corecord/dev/domain/ability/domain/converter/AbilityConverter.java
  src/main/java/corecord/dev/domain/ability/domain/dto/response/AbilityResponse.java
  src/main/java/corecord/dev/domain/ability/domain/entity/Ability.java
  src/main/java/corecord/dev/domain/ability/domain/enums/Keyword.java
  src/main/java/corecord/dev/domain/ability/domain/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/domain/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/domain/dto/response/AnalysisResponse.java
  src/main/java/corecord/dev/domain/feedback/application/FeedbackAlarmSender.java
  src/main/java/corecord/dev/domain/feedback/application/FeedbackDbService.java
  src/main/java/corecord/dev/domain/feedback/application/FeedbackService.java
  src/main/java/corecord/dev/domain/feedback/application/FeedbackServiceImpl.java
  src/main/java/corecord/dev/domain/feedback/domain/converter/FeedbackConverter.java
  src/main/java/corecord/dev/domain/feedback/domain/dto/request/FeedbackRequest.java
  src/main/java/corecord/dev/domain/feedback/domain/entity/Feedback.java
  src/main/java/corecord/dev/domain/feedback/domain/enums/FeedbackType.java
  src/main/java/corecord/dev/domain/feedback/domain/enums/Issue.java
  src/main/java/corecord/dev/domain/feedback/domain/enums/Satisfaction.java
  src/main/java/corecord/dev/domain/feedback/domain/exception/FeedbackException.java
  src/main/java/corecord/dev/domain/feedback/domain/repository/FeedbackRepository.java
  src/main/java/corecord/dev/domain/feedback/domain/status/FeedbackErrorStatus.java
  src/main/java/corecord/dev/domain/feedback/domain/status/FeedbackSuccessStatus.java
  src/main/java/corecord/dev/domain/feedback/infra/notification/converter/FeedbackAlarmConverter.java
  src/main/java/corecord/dev/domain/feedback/infra/notification/discord/FeedbackDiscordAlarmSender.java
  src/main/java/corecord/dev/domain/feedback/infra/notification/discord/FeedbackDiscordUtil.java
  src/main/java/corecord/dev/domain/feedback/infra/notification/dto/FeedbackAlarmDto.java
  src/main/java/corecord/dev/domain/feedback/presentation/FeedbackController.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/application/RecordServiceImpl.java
  src/main/java/corecord/dev/domain/record/domain/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/domain/dto/request/RecordRequest.java
  src/main/java/corecord/dev/domain/record/domain/entity/Record.java
  src/main/java/corecord/dev/domain/record/domain/entity/RecordType.java
  src/main/java/corecord/dev/domain/record/domain/enums/RecordType.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/user/application/UserServiceImpl.java
  src/main/java/corecord/dev/domain/user/domain/converter/UserConverter.java
  src/main/java/corecord/dev/domain/user/domain/entity/User.java
  src/main/java/corecord/dev/domain/user/domain/enums/Status.java
  src/test/java/corecord/dev/ability/service/AbilityServiceTest.java
  src/test/java/corecord/dev/analysis/service/AnalysisServiceTest.java
  src/test/java/corecord/dev/chat/repository/ChatRepositoryTest.java
  src/test/java/corecord/dev/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/corecord/dev/chat/service/ChatServiceTest.java
  src/test/java/corecord/dev/folder/repository/FolderRepositoryTest.java
  src/test/java/corecord/dev/folder/service/FolderServiceTest.java
  src/test/java/corecord/dev/record/memo/repository/MemoRecordRepositoryTest.java
  src/test/java/corecord/dev/record/memo/service/MemoRecordServiceTest.java
  src/test/java/corecord/dev/user/repository/UserRepositoryTest.java
  src/test/java/corecord/dev/user/service/UserServiceTest.java
Labels: Feat 💙

#24 [Chore/#23] 경험 기록 API Response DTO 수정 및 Analysis-Ability FETCH TYPE 변경
  src/main/java/corecord/dev/domain/ability/application/AbilityServiceImpl.java
  src/main/java/corecord/dev/domain/analysis/domain/entity/Analysis.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/application/RecordService.java
  src/main/java/corecord/dev/domain/record/application/RecordServiceImpl.java
  src/main/java/corecord/dev/domain/record/domain/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/domain/dto/response/RecordResponse.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/presentation/RecordController.java
  src/main/java/corecord/dev/domain/record/status/RecordSuccessStatus.java
  src/main/java/corecord/dev/domain/user/application/UserServiceImpl.java
  src/test/java/corecord/dev/user/service/UserServiceTest.java
Labels: Chore ⚙️

#28 [Fix/#27] 서버 에러 발생 시 AOP 감지 문제 해결
  src/main/java/corecord/dev/common/config/AspectConfig.java
  src/main/java/corecord/dev/common/log/discord/DiscordLoggerAop.java
Labels: Fix 🛠️
