Repository KUSITMS-MOAMOA/MOAMOA_BE_V2, pull requests merged in 2025-03, with the labels that each got.

#30 [Feat/#29] : Test 서버 추가
  .github/workflows/cicd-test.yml
  .github/workflows/cicd.yml
Labels: Feat 💙

#34 [Feat/#33] 예시용 가이드 채팅 생성 기능 구현
  src/main/java/corecord/dev/common/util/ResourceLoader.java
  src/main/java/corecord/dev/domain/ability/application/AbilityService.java
  src/main/java/corecord/dev/domain/ability/application/AbilityServiceImpl.java
  src/main/java/corecord/dev/domain/ability/domain/converter/AbilityConverter.java
  src/main/java/corecord/dev/domain/ability/domain/entity/Ability.java
  src/main/java/corecord/dev/domain/ability/domain/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisService.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisServiceImpl.java
  src/main/java/corecord/dev/domain/chat/application/ChatService.java
  src/main/java/corecord/dev/domain/chat/application/ChatServiceImpl.java
  src/main/java/corecord/dev/domain/folder/application/FolderService.java
  src/main/java/corecord/dev/domain/folder/application/FolderServiceImpl.java
  src/main/java/corecord/dev/domain/record/application/RecordService.java
  src/main/java/corecord/dev/domain/record/application/RecordServiceImpl.java
  src/main/java/corecord/dev/domain/record/domain/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/domain/entity/Record.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/user/application/UserServiceImpl.java
  src/main/resources/example-record.json
Labels: Feat 💙

#39 [Chore/#37] 예시 경험 폴더 조회 범위 수정
  src/main/java/corecord/dev/domain/folder/application/FolderServiceImpl.java
  src/main/java/corecord/dev/domain/folder/domain/repository/FolderRepository.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
Labels: Chore ⚙️

#42 [Refactor/#41] AI 관련 에러 코드 변경 및 최근 경험 기록 조회 API 수정
  src/main/java/corecord/dev/domain/chat/status/ChatErrorStatus.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/application/RecordServiceImpl.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
Labels: Refactor🌿

#45 [Fix/#44] : jwtFilter와 securityConfig에 OAuth url 제외 처리
  src/main/java/corecord/dev/common/config/SecurityConfig.java
  src/main/java/corecord/dev/domain/auth/jwt/JwtFilter.java
Labels: Fix 🛠️

#48 [Chore/#47] 역량 분석 AI 관련 에러 코드 수정
  src/main/java/corecord/dev/domain/analysis/status/AnalysisErrorStatus.java
  src/main/java/corecord/dev/domain/chat/application/ChatServiceImpl.java
  src/main/java/corecord/dev/domain/chat/domain/entity/Chat.java
Labels: Chore ⚙️

#50 [Chore/#37] 예시 경험 폴더명 ENUM 생성
  src/main/java/corecord/dev/domain/folder/application/FolderServiceImpl.java
  src/main/java/corecord/dev/domain/folder/domain/enums/ExampleFolder.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/domain/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/domain/entity/Record.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
  src/test/java/corecord/dev/record/memo/repository/MemoRecordRepositoryTest.java
Labels: Chore ⚙️

#52 [Refactor/#51] 경험 기록 조회 API 수정
  src/main/java/corecord/dev/domain/ability/domain/entity/Ability.java
  src/main/java/corecord/dev/domain/ability/domain/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/domain/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/chat/application/ChatServiceImpl.java
  src/main/java/corecord/dev/domain/chat/domain/converter/ChatConverter.java
  src/main/java/corecord/dev/domain/chat/domain/entity/Chat.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/application/RecordServiceImpl.java
  src/main/java/corecord/dev/domain/record/domain/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/domain/entity/Record.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
Labels: Refactor🌿

#55 [Fix/#54] : redis 분산락으로 회원가입 시 중복 유저 생성 문제 해결
  src/main/java/corecord/dev/common/util/RedisLockUtil.java
  src/main/java/corecord/dev/domain/user/application/UserServiceImpl.java
Labels: Fix 🛠️
