Repository KUSITMS-MOAMOA/MOAMOA_BE_V2, pull requests merged in 2025-01, with the labels that each got.

#2 [Refactor/#1] : CI/CD 파이프라인 수정
  .github/workflows/cicd.yml
  Dockerfile
Labels: Refactor🌿

#3 [Fix]: gradle build 순서 파일 생성 후로 이동
  .github/workflows/cicd.yml
Labels: Fix 🛠️

#5 [Feat/#4] 에러 발생 시 Discord 알림 전송 기능 구현
  build.gradle
  src/main/java/corecord/dev/common/exception/GeneralException.java
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/common/log/discord/DiscordAlarmSender.java
  src/main/java/corecord/dev/common/log/discord/DiscordLoggerAop.java
  src/main/java/corecord/dev/common/log/discord/DiscordUtil.java
  src/main/java/corecord/dev/common/log/discord/dto/DiscordDto.java
  src/main/java/corecord/dev/domain/ability/exception/AbilityException.java
  src/main/java/corecord/dev/domain/analysis/exception/AnalysisException.java
  src/main/java/corecord/dev/domain/analysis/status/AnalysisErrorStatus.java
  src/main/java/corecord/dev/domain/auth/exception/TokenException.java
  src/main/java/corecord/dev/domain/auth/jwt/JwtFilter.java
  src/main/java/corecord/dev/domain/chat/exception/ChatException.java
  src/main/java/corecord/dev/domain/folder/exception/FolderException.java
  src/main/java/corecord/dev/domain/record/exception/RecordException.java
  src/main/java/corecord/dev/domain/user/exception/UserException.java
Labels: Feat 💙

#8 [Chore/#7] 디스코드 알림 범위 축소
  src/main/java/corecord/dev/common/log/discord/DiscordLoggerAop.java
Labels: Chore ⚙️

#9 [Refactor/#6] 성능 개선을 위한 인덱스 추가
  src/main/java/corecord/dev/domain/ability/domain/entity/Ability.java
  src/main/java/corecord/dev/domain/analysis/domain/entity/Analysis.java
  src/main/java/corecord/dev/domain/folder/domain/entity/Folder.java
  src/main/java/corecord/dev/domain/record/domain/entity/Record.java
Labels: Refactor🌿
